# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocientifico',
            name='id',
        ),
        migrations.AddField(
            model_name='eventocientifico',
            name='evento_ptr',
            field=models.OneToOneField(auto_created=True, default='2011-09-01T13:20:30', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evento.Evento'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='artigocientifico',
            name='autores',
        ),
        migrations.AddField(
            model_name='artigocientifico',
            name='autores',
            field=models.ManyToManyField(to='evento.Autor'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='dataEHoraDeInicio',
            field=models.DateTimeField(verbose_name=datetime.datetime(2017, 4, 3, 22, 58, 16, 557189, tzinfo=utc)),
        ),
    ]
